### PR TITLE
Add integration test

### PR DESCRIPTION
**Pull request by vubogovich**
## What

Added script to test the integration of the package with the real Airtable base.

## Why

It's not easy to test the package without the real Airtable API so some bugs can sneak into the source code.

## How

The script can be run locally once `.env` defines the table in an Airtable base which can be used to create new records.

It will try to create, update, replace and fetch a record and then delete it even if some operation fails so the table stays clean.

## Testing

See README.md

## Who is affected

Nobody as the script is not included into the build artifacts or any other process.

---
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/airtable/60)

### CODE REVIEW

**Review by gsuess — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/60)* status: all files reviewed, 1 unresolved discussion (waiting on @vubogovich)

___
*[.env.example, line 4 at r1](https://reviewable.io/reviews/qualifyze/airtable/60#-Me4hhIMEnXuS_6OBK3J:-Me4hhIMEnXuS_6OBK3K:b-87pbd5) ([raw file](https://github.com/qualifyze/airtable/blob/a6c9ae352cdbca652a5f9661d210250a6d6a855b/.env.example#L4)):*
> ```Shell
> AIRTABLE_BASE_ID=
> TEST_TABLE_NAME=auditee
> TEST_FIELD_NAMES=companyName,address
> ```

Given that this client supports field-validations, I think the best way the approach this is to use the [ajv](https://www.npmjs.com/package/ajv)  package to read a JSON schema file for a table that you are testing.

**Review by vubogovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/60)* status: all files reviewed, 1 unresolved discussion (waiting on @gsuess)

___
*[.env.example, line 4 at r1](https://reviewable.io/reviews/qualifyze/airtable/60#-Me4hhIMEnXuS_6OBK3J:-Me5Du7K7CcENOr2_aTk:b-95n6cj) ([raw file](https://github.com/qualifyze/airtable/blob/a6c9ae352cdbca652a5f9661d210250a6d6a855b/.env.example#L4)):*
<details><summary><i>Previously, gsuess (Garik Suess) wrote…</i></summary><blockquote>

Given that this client supports field-validations, I think the best way the approach this is to use the [ajv](https://www.npmjs.com/package/ajv)  package to read a JSON schema file for a table that you are testing.
</blockquote></details>

Good idea for the next iteration! I think it would be too much for this PR as the current version is already a good step forward, very simple to use and not a priority (since moving away from airtable).

**Review by gsuess — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/60)* status: all files reviewed, 1 unresolved discussion (waiting on @vubogovich)

___
*[.env.example, line 4 at r1](https://reviewable.io/reviews/qualifyze/airtable/60#-Me4hhIMEnXuS_6OBK3J:-Me5kGXqCTrsfhRRbbw9:b1iyrsl) ([raw file](https://github.com/qualifyze/airtable/blob/a6c9ae352cdbca652a5f9661d210250a6d6a855b/.env.example#L4)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

Good idea for the next iteration! I think it would be too much for this PR as the current version is already a good step forward, very simple to use and not a priority (since moving away from airtable).
</blockquote></details>

I agree, but please add an inline comment here, so that this pattern doesn't replicate.

**Review by vubogovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/60)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @gsuess)

___
*[.env.example, line 4 at r1](https://reviewable.io/reviews/qualifyze/airtable/60#-Me4hhIMEnXuS_6OBK3J:-Me6h71o9CNfNRHVqPZa:b-9d5j81) ([raw file](https://github.com/qualifyze/airtable/blob/a6c9ae352cdbca652a5f9661d210250a6d6a855b/.env.example#L4)):*
<details><summary><i>Previously, gsuess (Garik Suess) wrote…</i></summary><blockquote>

I agree, but please add an inline comment here, so that this pattern doesn't replicate.
</blockquote></details>

Right! Added in 2 places.

**Review by gsuess — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/60)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vubogovich)

**Pull request merged**
