### PR TITLE
Initial Implementation, v1.0.0

### PR DESCRIPTION
**Pull request by gsuess**
See Readme.

---
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/airtable/1)

### CODE REVIEW

**Review by sirJiggles — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/1)* status: all files reviewed, 10 unresolved discussions (waiting on @gsuess)

*[a discussion](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKizkEEnJ03gidULpK:-MYKizkFEpfWO-krVR29:b6cmxe0) (no related file):*
This is really really cool, sorry it took so long I had to look up a ton of things I did not know you could do in TS so I learnt a ton looking at this PR :sunglasses: 

I tried to be as thorough as I could but for me it is all looking good so far I would like to give it a battle test tomorrow and actually try use it but for now I can already post my comments.

The naming of runAction had me a little confused sometimes as there is the same function in a base, record, table and so on. sometimes I was not sure which runAction was running.

also as the base has one but the official client it wraps it has one, so the endpoint inside the base instance. I mean I figured it out so maybe it is just this case as I was looking at the whole thing in one go. so not sure if it is an issue tbh, just thought I would share.

---
___
*[jest.config.ts, line 65 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKKN5pEjYKYhDU0Czi:-MYKKN5pEjYKYhDU0Czj:b8uy5px) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/jest.config.ts#L65)):*
> ```XML
>   globals: {
>     "ts-jest": {
>       compiler: "ttypescript",
> ```

looks like a typo here
___
*[jest.config.ts, line 153 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKKiEU31h6CcNnqW9L:-MYKKiEV4f-1kw4Ohb6r:b-xw5dc9) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/jest.config.ts#L153)):*
> ```XML
> 
>   // The glob patterns Jest uses to detect test files
>   testMatch: ["**/test/**/*.[jt]s?(x)"],
> ```

should it be [jt]?
___
*[Readme.md, line 146 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKMcGe5JQG65LujZvY:-MYKMcGe5JQG65LujZvZ:b5ihb8p) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/Readme.md#L146)):*
> ```Markdown
> ```
> 
> There are no `.set()` or `.get()` methods on the Record API.
> ```

this looks soo cool :tada: 
___
*[.github/workflows/deploy.yml, line 16 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKMHpACh-ChJQ7-SPC:-MYKMHpACh-ChJQ7-SPD:b-jr711j) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/.github/workflows/deploy.yml#L16)):*
> ```YAML
>         run: npm run test
>       - name: Run Build
>         run: npm run build
> ```

do you need to do `npm deploy`? as it looks like this is just going to build it and not deploy
___
*[.github/workflows/deploy.yml, line 19 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKLxQDCgOEydxhSa2O:-MYKLxQDCgOEydxhSa2P:b-2tp1rf) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/.github/workflows/deploy.yml#L19)):*
> ```YAML
>       - uses: Qualifyze/npm-publish@v1
>         with:
>           token: ${{ secrets.NPM_TOKEN }}
> ```

is this our new npm org? if so how would I also use something like this in the future if I want to make my own repo?

and does this mean that this will be open source?
___
*[src/endpoint.ts, line 1 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKdQTp0ghOSKSIsCyq:-MYKdQTp0ghOSKSIsCyr:bq5fbn5) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/src/endpoint.ts#L1)):*
> ```XML
> type UnknownBody = Record<string, unknown>;
> ```

Maybe outside of the PR you could help me understand why string | unknown is better than just unknown?

as I was thinking if it is an unknown type that happens to be string you will still not be able to cast it to anything else right?
___
*[src/fields.ts, line 3 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKfZ5uA0T93ooqqTFk:-MYKfZ5uA0T93ooqqTFl:b6y82v1) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/src/fields.ts#L3)):*
> ```XML
> import { Validator } from "./validator";
> 
> export type UnknownFields = Record<Exclude<string, "id">, unknown>;
> ```

would unknown also include the string "id"? and how come we would like to exclude it?
___
*[src/record.ts, line 83 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKkwsb45paAcge-BCa:-MYKkwsb45paAcge-BCb:b-ec6oie) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/src/record.ts#L83)):*
> ```XML
>   }
> 
>   destroy(): Promise<DeletedRecord> {
> ```

I guess you do not need to pass ID for the delete action as it is stored on the instance of the record and you will pass it to the source runAction command right?
___
*[src/table.ts, line 13 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKgcyE9kZ6Ps-hwIjp:-MYKgcyE9kZ6Ps-hwIjq:bbfhn7a) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/src/table.ts#L13)):*
> ```XML
> import { MultiRecordResponseValidation } from "./raw-types";
> 
> export type TableDataSource = ActionPoint;
> ```

How come we make a new type here that is a new name for another type? it is to make it easier to read?
___
*[src/table.ts, line 98 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKhuSk6DzAm9RqG1wi:-MYKhuSk6DzAm9RqG1wj:b-1oij6f) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/src/table.ts#L98)):*
> ```XML
>   }
> 
>   create(data: Fields): Promise<AirtableRecord<Fields>>;
> ```

did not know you could do function overloading like this in TS, very cool :sunglasses: 
___
*[src/table.ts, line 183 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKmgeVAqacJcXz9SjC:-MYKmgeWD7SpigsMgmq2:b-9z1ame) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/src/table.ts#L183)):*
> ```XML
>   }
> 
>   private async destroyMultipleRecords(
> ```

could we also recursively run through the id's and `destroySingleRecord()` on them? as that uses the runAction inside the record right. Or did you do it like this so that it is just one call to the API
___
*[src/raw-types/deleted-record.ts, line 19 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKobVX64Bkp4k-boQv:-MYKobVX64Bkp4k-boQw:b-xkqnlt) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/src/raw-types/deleted-record.ts#L19)):*
> ```XML
> 
>   // eslint-disable-next-line @typescript-eslint/ban-types
>   static hasDeleted(subject: object): subject is { deleted: unknown } {
> ```

again very very cool I did not know you could do this :tada:

**Review by sirJiggles — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/1)* status: all files reviewed, 9 unresolved discussions (waiting on @gsuess)

___
*[src/endpoint.ts, line 1 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKdQTp0ghOSKSIsCyq:-MYL84ZoBQP-Bj9adztK:bwnrx12) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/src/endpoint.ts#L1)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

Maybe outside of the PR you could help me understand why string | unknown is better than just unknown?

as I was thinking if it is an unknown type that happens to be string you will still not be able to cast it to anything else right?
</blockquote></details>

Ignore this we spoke about this already

**Review by gsuess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/1)* status: all files reviewed, 9 unresolved discussions (waiting on @gsuess and @sirJiggles)

___
*[jest.config.ts, line 65 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKKN5pEjYKYhDU0Czi:-MYL8d1J0CLti197fSKg:b-ureq1d) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/jest.config.ts#L65)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

looks like a typo here
</blockquote></details>

it's not: https://www.npmjs.com/package/ttypescript

It's needed for ts-auto-mock, because that package needs to convert type definitions into actual runtime-constructs.
___
*[jest.config.ts, line 153 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKKiEU31h6CcNnqW9L:-MYL92az1h0FT4tJzJAU:b-ktgbtv) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/jest.config.ts#L153)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

should it be [jt]?
</blockquote></details>

js, ts, jsx or tsx, yes.
___
*[.github/workflows/deploy.yml, line 16 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKMHpACh-ChJQ7-SPC:-MYL9Leq8_2tY9guHWjr:b-7bmyxx) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/.github/workflows/deploy.yml#L16)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

do you need to do `npm deploy`? as it looks like this is just going to build it and not deploy
</blockquote></details>

This exactly what the next line does, except that will first check if the version is already published and only publish it if it was not published yet.
___
*[.github/workflows/deploy.yml, line 19 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKLxQDCgOEydxhSa2O:-MYL9Y-a5ZPjqyrIzNQw:bra63ul) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/.github/workflows/deploy.yml#L19)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

is this our new npm org? if so how would I also use something like this in the future if I want to make my own repo?

and does this mean that this will be open source?
</blockquote></details>

https://github.com/Qualifyze/npm-publish

It is open-source already, we are just using a fork: https://chemsquare.slack.com/archives/C89L7PP1C/p1601891889008200
___
*[src/fields.ts, line 3 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKfZ5uA0T93ooqqTFk:-MYL9emU6DD7DhyF3g3v:b-2hulde) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/src/fields.ts#L3)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

would unknown also include the string "id"? and how come we would like to exclude it?
</blockquote></details>

It just means that the key must not be "id". But this is quite inconsequential - typescript doesn't will resolve this a as `string` anyway, so I can remove that part.
___
*[src/record.ts, line 83 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKkwsb45paAcge-BCa:-MYLA5lX1twQS2_Gu0yG:b-6z6nar) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/src/record.ts#L83)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

I guess you do not need to pass ID for the delete action as it is stored on the instance of the record and you will pass it to the source runAction command right?
</blockquote></details>

This action is run on `this` (the record instance).
___
*[src/table.ts, line 13 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKgcyE9kZ6Ps-hwIjp:-MYLAa1RB41KNYPCb9vs:b9e42gi) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/src/table.ts#L13)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

How come we make a new type here that is a new name for another type? it is to make it easier to read?
</blockquote></details>

This is a single source of truth of what the Data-Source of the table should be. There is also RecordDataSource for records, which is more than just ActionPoint. So it also provides some symmetry in the patterns.

It makes it easier to change key decisions on how things are implemented. So basically it reduces code churn. The name is also more descriptive of the purpose of the argument. If the name wouldn't work out then I would argue it should not be aliased out. 
___
*[src/table.ts, line 183 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKmgeVAqacJcXz9SjC:-MYLBfMFEIsM2aMVOadg:b-nqpjlc) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/src/table.ts#L183)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

could we also recursively run through the id's and `destroySingleRecord()` on them? as that uses the runAction inside the record right. Or did you do it like this so that it is just one call to the API
</blockquote></details>

One call to the API, means it will be significantly faster.

**Review by gsuess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/1)* status: all files reviewed, 9 unresolved discussions (waiting on @sirJiggles)

*[a discussion](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKizkEEnJ03gidULpK:-MYLCldI66Zu6cqwcg17:b1qbd9i) (no related file):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

This is really really cool, sorry it took so long I had to look up a ton of things I did not know you could do in TS so I learnt a ton looking at this PR :sunglasses: 

I tried to be as thorough as I could but for me it is all looking good so far I would like to give it a battle test tomorrow and actually try use it but for now I can already post my comments.

The naming of runAction had me a little confused sometimes as there is the same function in a base, record, table and so on. sometimes I was not sure which runAction was running.

also as the base has one but the official client it wraps it has one, so the endpoint inside the base instance. I mean I figured it out so maybe it is just this case as I was looking at the whole thing in one go. so not sure if it is an issue tbh, just thought I would share.


</blockquote></details>

This is because there are 3 implementations of the `ActionPoint` interface. Naming the method the same way is necessary for the Liskov Substitution Principle. 

---

**Review by gsuess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/1)* status: 24 of 30 files reviewed, 8 unresolved discussions (waiting on @sirJiggles)

*[a discussion](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKizkEEnJ03gidULpK:-MYLP0-C9cLT6xnnyl5w:b3rq103) (no related file):*
<details><summary><i>Previously, gsuess (Garik Suess) wrote…</i></summary><blockquote>

This is because there are 3 implementations of the `ActionPoint` interface. Naming the method the same way is necessary for the Liskov Substitution Principle. 
</blockquote></details>

Turns out that having them share the same interface is not valuable after all. So I gave them a different interface.

---

**Review by sirJiggles — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/1)* status: all files reviewed, 2 unresolved discussions (waiting on @sirJiggles)

___
*[jest.config.ts, line 153 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKKiEU31h6CcNnqW9L:-MYOZmMC3g0d2K18CqoS:b8p0jca) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/jest.config.ts#L153)):*
<details><summary><i>Previously, gsuess (Garik Suess) wrote…</i></summary><blockquote>

js, ts, jsx or tsx, yes.
</blockquote></details>

ahh sorry I see now :/

**Review by sirJiggles — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gsuess)

___
*[.github/workflows/deploy.yml, line 19 at r1](https://reviewable.io/reviews/qualifyze/airtable/1#-MYKLxQDCgOEydxhSa2O:-MYOZzTeAkgoobIqn_P2:b-kcopoq) ([raw file](https://github.com/qualifyze/airtable/blob/6585628e1f2f2ff06ee4f4774648959dde5092ae/.github/workflows/deploy.yml#L19)):*
> https://github.com/Qualifyze/npm-publish
nice! 🚀

**Review by falco953 — APPROVED** [review]
Took me a while to get through it, but looks really nice! Couldn't find anything to complain, looking forward using it 😊 

> Reviewed 24 of 30 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/1#-:-MYOe0di9YjLT36zQwXj:bhbwrxi)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gsuess)

**Pull request merged**
