### PR TITLE
Improve data validations

### PR DESCRIPTION
**Pull request by vubogovich**
- make the final error message more concise
- include record id to the record validation context
- don't stop validating multiple records on first error
- cover with tests

### CODE REVIEW

**Review by gsuess — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/89)* status: all files reviewed, 1 unresolved discussion (waiting on @vubogovich)

___
*[src/test/table.ts, line 131 at r1](https://reviewable.io/reviews/qualifyze/airtable/89#-MujT2vo2bPHDD0JymLy:-MujT2vo2bPHDD0JymLz:b-cen6ev) ([raw file](https://github.com/qualifyze/airtable/blob/70114006742ba9764d3e5845c3fed1342fbad750/src/test/table.ts#L131)):*
> ```XML
>     const table = new Table<SomeData>(base, "invalid-table", validator);
> 
>     await expect(table.select({}).getPage()).rejects.toHaveProperty(
> ```

https://jestjs.io/docs/expect#tothrowerrormatchinginlinesnapshotinlinesnapshot

would be easier to read and maintain imho.

**Review by vubogovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/89)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @gsuess)

___
*[src/test/table.ts, line 131 at r1](https://reviewable.io/reviews/qualifyze/airtable/89#-MujT2vo2bPHDD0JymLy:-MvJY78R6OAfYGawfdo5:b-jet526) ([raw file](https://github.com/qualifyze/airtable/blob/70114006742ba9764d3e5845c3fed1342fbad750/src/test/table.ts#L131)):*
<details><summary><i>Previously, gsuess (Garik Suess) wrote…</i></summary><blockquote>

https://jestjs.io/docs/expect#tothrowerrormatchinginlinesnapshotinlinesnapshot

would be easier to read and maintain imho.
</blockquote></details>

Definitely, thanks for the hint! I didn't know jest can inject the snapshots :facepalm:  But for this TDD I would need to do it myself.

**Review by vubogovich — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/89)* status: all files reviewed, 1 unresolved discussion (waiting on @gsuess)

**Review by vubogovich — COMMENTED** [review]
> Dismissed @gsuess from a discussion.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vubogovich)

**Pull request merged**
